/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SystemMailRouteImport } from './routes/system-mail'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MailMarketingRouteImport } from './routes/mail-marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as B2bRequestsRouteImport } from './routes/b2b-requests'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as SegmentsIndexRouteImport } from './routes/segments/index'
import { Route as TeamUsersRouteImport } from './routes/team/users'
import { Route as TeamRolesRouteImport } from './routes/team/roles'
import { Route as TeamCommissionsRouteImport } from './routes/team/commissions'
import { Route as TasksSalesRouteImport } from './routes/tasks/sales'
import { Route as TasksMessagesRouteImport } from './routes/tasks/messages'
import { Route as TasksEmailRouteImport } from './routes/tasks/email'
import { Route as TasksCustomerRouteImport } from './routes/tasks/customer'
import { Route as TasksCalendarRouteImport } from './routes/tasks/calendar'
import { Route as SettingsWorkspaceRouteImport } from './routes/settings/workspace'
import { Route as SettingsShopifyRouteImport } from './routes/settings/shopify'
import { Route as SettingsAircallRouteImport } from './routes/settings/aircall'
import { Route as SettingsAiRouteImport } from './routes/settings/ai'
import { Route as TeamUsersIndexRouteImport } from './routes/team/users.index'
import { Route as TeamUsersAddRouteImport } from './routes/team/users.add'
import { Route as SettingsAircallWebhooksRouteImport } from './routes/settings/aircall/webhooks'
import { Route as SettingsAircallUsersRouteImport } from './routes/settings/aircall/users'
import { Route as SettingsAircallSyncLogsRouteImport } from './routes/settings/aircall/sync-logs'
import { Route as SettingsAircallNumbersRouteImport } from './routes/settings/aircall/numbers'
import { Route as SettingsAircallConnectionRouteImport } from './routes/settings/aircall/connection'
import { Route as SettingsAiUsageLogRouteImport } from './routes/settings/ai/usage-log'
import { Route as SettingsAiTasksRouteImport } from './routes/settings/ai/tasks'
import { Route as SettingsAiSettingsRouteImport } from './routes/settings/ai/settings'
import { Route as SettingsAiServicesRouteImport } from './routes/settings/ai/services'
import { Route as SettingsAiPromptsRouteImport } from './routes/settings/ai/prompts'
import { Route as SettingsAiHealthRouteImport } from './routes/settings/ai/health'
import { Route as SettingsAiBudgetRouteImport } from './routes/settings/ai/budget'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemMailRoute = SystemMailRouteImport.update({
  id: '/system-mail',
  path: '/system-mail',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MailMarketingRoute = MailMarketingRouteImport.update({
  id: '/mail-marketing',
  path: '/mail-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRequestsRoute = B2bRequestsRouteImport.update({
  id: '/b2b-requests',
  path: '/b2b-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const SegmentsIndexRoute = SegmentsIndexRouteImport.update({
  id: '/segments/',
  path: '/segments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamUsersRoute = TeamUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => TeamRoute,
} as any)
const TeamRolesRoute = TeamRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => TeamRoute,
} as any)
const TeamCommissionsRoute = TeamCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => TeamRoute,
} as any)
const TasksSalesRoute = TasksSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => TasksRoute,
} as any)
const TasksMessagesRoute = TasksMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TasksRoute,
} as any)
const TasksEmailRoute = TasksEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => TasksRoute,
} as any)
const TasksCustomerRoute = TasksCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => TasksRoute,
} as any)
const TasksCalendarRoute = TasksCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TasksRoute,
} as any)
const SettingsWorkspaceRoute = SettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsShopifyRoute = SettingsShopifyRouteImport.update({
  id: '/shopify',
  path: '/shopify',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAircallRoute = SettingsAircallRouteImport.update({
  id: '/aircall',
  path: '/aircall',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SettingsRoute,
} as any)
const TeamUsersIndexRoute = TeamUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamUsersRoute,
} as any)
const TeamUsersAddRoute = TeamUsersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => TeamUsersRoute,
} as any)
const SettingsAircallWebhooksRoute = SettingsAircallWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => SettingsAircallRoute,
} as any)
const SettingsAircallUsersRoute = SettingsAircallUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsAircallRoute,
} as any)
const SettingsAircallSyncLogsRoute = SettingsAircallSyncLogsRouteImport.update({
  id: '/sync-logs',
  path: '/sync-logs',
  getParentRoute: () => SettingsAircallRoute,
} as any)
const SettingsAircallNumbersRoute = SettingsAircallNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => SettingsAircallRoute,
} as any)
const SettingsAircallConnectionRoute =
  SettingsAircallConnectionRouteImport.update({
    id: '/connection',
    path: '/connection',
    getParentRoute: () => SettingsAircallRoute,
  } as any)
const SettingsAiUsageLogRoute = SettingsAiUsageLogRouteImport.update({
  id: '/usage-log',
  path: '/usage-log',
  getParentRoute: () => SettingsAiRoute,
} as any)
const SettingsAiTasksRoute = SettingsAiTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => SettingsAiRoute,
} as any)
const SettingsAiSettingsRoute = SettingsAiSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SettingsAiRoute,
} as any)
const SettingsAiServicesRoute = SettingsAiServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SettingsAiRoute,
} as any)
const SettingsAiPromptsRoute = SettingsAiPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => SettingsAiRoute,
} as any)
const SettingsAiHealthRoute = SettingsAiHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => SettingsAiRoute,
} as any)
const SettingsAiBudgetRoute = SettingsAiBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => SettingsAiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b2b-requests': typeof B2bRequestsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mail-marketing': typeof MailMarketingRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/system-mail': typeof SystemMailRoute
  '/tasks': typeof TasksRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/settings/ai': typeof SettingsAiRouteWithChildren
  '/settings/aircall': typeof SettingsAircallRouteWithChildren
  '/settings/shopify': typeof SettingsShopifyRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/tasks/customer': typeof TasksCustomerRoute
  '/tasks/email': typeof TasksEmailRoute
  '/tasks/messages': typeof TasksMessagesRoute
  '/tasks/sales': typeof TasksSalesRoute
  '/team/commissions': typeof TeamCommissionsRoute
  '/team/roles': typeof TeamRolesRoute
  '/team/users': typeof TeamUsersRouteWithChildren
  '/segments/': typeof SegmentsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/settings/ai/budget': typeof SettingsAiBudgetRoute
  '/settings/ai/health': typeof SettingsAiHealthRoute
  '/settings/ai/prompts': typeof SettingsAiPromptsRoute
  '/settings/ai/services': typeof SettingsAiServicesRoute
  '/settings/ai/settings': typeof SettingsAiSettingsRoute
  '/settings/ai/tasks': typeof SettingsAiTasksRoute
  '/settings/ai/usage-log': typeof SettingsAiUsageLogRoute
  '/settings/aircall/connection': typeof SettingsAircallConnectionRoute
  '/settings/aircall/numbers': typeof SettingsAircallNumbersRoute
  '/settings/aircall/sync-logs': typeof SettingsAircallSyncLogsRoute
  '/settings/aircall/users': typeof SettingsAircallUsersRoute
  '/settings/aircall/webhooks': typeof SettingsAircallWebhooksRoute
  '/team/users/add': typeof TeamUsersAddRoute
  '/team/users/': typeof TeamUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b2b-requests': typeof B2bRequestsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mail-marketing': typeof MailMarketingRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/system-mail': typeof SystemMailRoute
  '/tasks': typeof TasksRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/settings/ai': typeof SettingsAiRouteWithChildren
  '/settings/aircall': typeof SettingsAircallRouteWithChildren
  '/settings/shopify': typeof SettingsShopifyRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/tasks/customer': typeof TasksCustomerRoute
  '/tasks/email': typeof TasksEmailRoute
  '/tasks/messages': typeof TasksMessagesRoute
  '/tasks/sales': typeof TasksSalesRoute
  '/team/commissions': typeof TeamCommissionsRoute
  '/team/roles': typeof TeamRolesRoute
  '/segments': typeof SegmentsIndexRoute
  '/support': typeof SupportIndexRoute
  '/settings/ai/budget': typeof SettingsAiBudgetRoute
  '/settings/ai/health': typeof SettingsAiHealthRoute
  '/settings/ai/prompts': typeof SettingsAiPromptsRoute
  '/settings/ai/services': typeof SettingsAiServicesRoute
  '/settings/ai/settings': typeof SettingsAiSettingsRoute
  '/settings/ai/tasks': typeof SettingsAiTasksRoute
  '/settings/ai/usage-log': typeof SettingsAiUsageLogRoute
  '/settings/aircall/connection': typeof SettingsAircallConnectionRoute
  '/settings/aircall/numbers': typeof SettingsAircallNumbersRoute
  '/settings/aircall/sync-logs': typeof SettingsAircallSyncLogsRoute
  '/settings/aircall/users': typeof SettingsAircallUsersRoute
  '/settings/aircall/webhooks': typeof SettingsAircallWebhooksRoute
  '/team/users/add': typeof TeamUsersAddRoute
  '/team/users': typeof TeamUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/b2b-requests': typeof B2bRequestsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mail-marketing': typeof MailMarketingRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/system-mail': typeof SystemMailRoute
  '/tasks': typeof TasksRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/settings/ai': typeof SettingsAiRouteWithChildren
  '/settings/aircall': typeof SettingsAircallRouteWithChildren
  '/settings/shopify': typeof SettingsShopifyRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/tasks/customer': typeof TasksCustomerRoute
  '/tasks/email': typeof TasksEmailRoute
  '/tasks/messages': typeof TasksMessagesRoute
  '/tasks/sales': typeof TasksSalesRoute
  '/team/commissions': typeof TeamCommissionsRoute
  '/team/roles': typeof TeamRolesRoute
  '/team/users': typeof TeamUsersRouteWithChildren
  '/segments/': typeof SegmentsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/settings/ai/budget': typeof SettingsAiBudgetRoute
  '/settings/ai/health': typeof SettingsAiHealthRoute
  '/settings/ai/prompts': typeof SettingsAiPromptsRoute
  '/settings/ai/services': typeof SettingsAiServicesRoute
  '/settings/ai/settings': typeof SettingsAiSettingsRoute
  '/settings/ai/tasks': typeof SettingsAiTasksRoute
  '/settings/ai/usage-log': typeof SettingsAiUsageLogRoute
  '/settings/aircall/connection': typeof SettingsAircallConnectionRoute
  '/settings/aircall/numbers': typeof SettingsAircallNumbersRoute
  '/settings/aircall/sync-logs': typeof SettingsAircallSyncLogsRoute
  '/settings/aircall/users': typeof SettingsAircallUsersRoute
  '/settings/aircall/webhooks': typeof SettingsAircallWebhooksRoute
  '/team/users/add': typeof TeamUsersAddRoute
  '/team/users/': typeof TeamUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/b2b-requests'
    | '/customers'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/mail-marketing'
    | '/orders'
    | '/pricing'
    | '/reset-password'
    | '/rules'
    | '/settings'
    | '/support'
    | '/system-mail'
    | '/tasks'
    | '/team'
    | '/settings/ai'
    | '/settings/aircall'
    | '/settings/shopify'
    | '/settings/workspace'
    | '/tasks/calendar'
    | '/tasks/customer'
    | '/tasks/email'
    | '/tasks/messages'
    | '/tasks/sales'
    | '/team/commissions'
    | '/team/roles'
    | '/team/users'
    | '/segments/'
    | '/support/'
    | '/settings/ai/budget'
    | '/settings/ai/health'
    | '/settings/ai/prompts'
    | '/settings/ai/services'
    | '/settings/ai/settings'
    | '/settings/ai/tasks'
    | '/settings/ai/usage-log'
    | '/settings/aircall/connection'
    | '/settings/aircall/numbers'
    | '/settings/aircall/sync-logs'
    | '/settings/aircall/users'
    | '/settings/aircall/webhooks'
    | '/team/users/add'
    | '/team/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/b2b-requests'
    | '/customers'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/mail-marketing'
    | '/orders'
    | '/pricing'
    | '/reset-password'
    | '/rules'
    | '/settings'
    | '/system-mail'
    | '/tasks'
    | '/team'
    | '/settings/ai'
    | '/settings/aircall'
    | '/settings/shopify'
    | '/settings/workspace'
    | '/tasks/calendar'
    | '/tasks/customer'
    | '/tasks/email'
    | '/tasks/messages'
    | '/tasks/sales'
    | '/team/commissions'
    | '/team/roles'
    | '/segments'
    | '/support'
    | '/settings/ai/budget'
    | '/settings/ai/health'
    | '/settings/ai/prompts'
    | '/settings/ai/services'
    | '/settings/ai/settings'
    | '/settings/ai/tasks'
    | '/settings/ai/usage-log'
    | '/settings/aircall/connection'
    | '/settings/aircall/numbers'
    | '/settings/aircall/sync-logs'
    | '/settings/aircall/users'
    | '/settings/aircall/webhooks'
    | '/team/users/add'
    | '/team/users'
  id:
    | '__root__'
    | '/'
    | '/b2b-requests'
    | '/customers'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/mail-marketing'
    | '/orders'
    | '/pricing'
    | '/reset-password'
    | '/rules'
    | '/settings'
    | '/support'
    | '/system-mail'
    | '/tasks'
    | '/team'
    | '/settings/ai'
    | '/settings/aircall'
    | '/settings/shopify'
    | '/settings/workspace'
    | '/tasks/calendar'
    | '/tasks/customer'
    | '/tasks/email'
    | '/tasks/messages'
    | '/tasks/sales'
    | '/team/commissions'
    | '/team/roles'
    | '/team/users'
    | '/segments/'
    | '/support/'
    | '/settings/ai/budget'
    | '/settings/ai/health'
    | '/settings/ai/prompts'
    | '/settings/ai/services'
    | '/settings/ai/settings'
    | '/settings/ai/tasks'
    | '/settings/ai/usage-log'
    | '/settings/aircall/connection'
    | '/settings/aircall/numbers'
    | '/settings/aircall/sync-logs'
    | '/settings/aircall/users'
    | '/settings/aircall/webhooks'
    | '/team/users/add'
    | '/team/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  B2bRequestsRoute: typeof B2bRequestsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MailMarketingRoute: typeof MailMarketingRoute
  OrdersRoute: typeof OrdersRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SupportRoute: typeof SupportRouteWithChildren
  SystemMailRoute: typeof SystemMailRoute
  TasksRoute: typeof TasksRouteWithChildren
  TeamRoute: typeof TeamRouteWithChildren
  SegmentsIndexRoute: typeof SegmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-mail': {
      id: '/system-mail'
      path: '/system-mail'
      fullPath: '/system-mail'
      preLoaderRoute: typeof SystemMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-marketing': {
      id: '/mail-marketing'
      path: '/mail-marketing'
      fullPath: '/mail-marketing'
      preLoaderRoute: typeof MailMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b-requests': {
      id: '/b2b-requests'
      path: '/b2b-requests'
      fullPath: '/b2b-requests'
      preLoaderRoute: typeof B2bRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/segments/': {
      id: '/segments/'
      path: '/segments'
      fullPath: '/segments/'
      preLoaderRoute: typeof SegmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/users': {
      id: '/team/users'
      path: '/users'
      fullPath: '/team/users'
      preLoaderRoute: typeof TeamUsersRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/roles': {
      id: '/team/roles'
      path: '/roles'
      fullPath: '/team/roles'
      preLoaderRoute: typeof TeamRolesRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/commissions': {
      id: '/team/commissions'
      path: '/commissions'
      fullPath: '/team/commissions'
      preLoaderRoute: typeof TeamCommissionsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/tasks/sales': {
      id: '/tasks/sales'
      path: '/sales'
      fullPath: '/tasks/sales'
      preLoaderRoute: typeof TasksSalesRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/messages': {
      id: '/tasks/messages'
      path: '/messages'
      fullPath: '/tasks/messages'
      preLoaderRoute: typeof TasksMessagesRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/email': {
      id: '/tasks/email'
      path: '/email'
      fullPath: '/tasks/email'
      preLoaderRoute: typeof TasksEmailRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/customer': {
      id: '/tasks/customer'
      path: '/customer'
      fullPath: '/tasks/customer'
      preLoaderRoute: typeof TasksCustomerRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/calendar': {
      id: '/tasks/calendar'
      path: '/calendar'
      fullPath: '/tasks/calendar'
      preLoaderRoute: typeof TasksCalendarRouteImport
      parentRoute: typeof TasksRoute
    }
    '/settings/workspace': {
      id: '/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof SettingsWorkspaceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/shopify': {
      id: '/settings/shopify'
      path: '/shopify'
      fullPath: '/settings/shopify'
      preLoaderRoute: typeof SettingsShopifyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/aircall': {
      id: '/settings/aircall'
      path: '/aircall'
      fullPath: '/settings/aircall'
      preLoaderRoute: typeof SettingsAircallRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/team/users/': {
      id: '/team/users/'
      path: '/'
      fullPath: '/team/users/'
      preLoaderRoute: typeof TeamUsersIndexRouteImport
      parentRoute: typeof TeamUsersRoute
    }
    '/team/users/add': {
      id: '/team/users/add'
      path: '/add'
      fullPath: '/team/users/add'
      preLoaderRoute: typeof TeamUsersAddRouteImport
      parentRoute: typeof TeamUsersRoute
    }
    '/settings/aircall/webhooks': {
      id: '/settings/aircall/webhooks'
      path: '/webhooks'
      fullPath: '/settings/aircall/webhooks'
      preLoaderRoute: typeof SettingsAircallWebhooksRouteImport
      parentRoute: typeof SettingsAircallRoute
    }
    '/settings/aircall/users': {
      id: '/settings/aircall/users'
      path: '/users'
      fullPath: '/settings/aircall/users'
      preLoaderRoute: typeof SettingsAircallUsersRouteImport
      parentRoute: typeof SettingsAircallRoute
    }
    '/settings/aircall/sync-logs': {
      id: '/settings/aircall/sync-logs'
      path: '/sync-logs'
      fullPath: '/settings/aircall/sync-logs'
      preLoaderRoute: typeof SettingsAircallSyncLogsRouteImport
      parentRoute: typeof SettingsAircallRoute
    }
    '/settings/aircall/numbers': {
      id: '/settings/aircall/numbers'
      path: '/numbers'
      fullPath: '/settings/aircall/numbers'
      preLoaderRoute: typeof SettingsAircallNumbersRouteImport
      parentRoute: typeof SettingsAircallRoute
    }
    '/settings/aircall/connection': {
      id: '/settings/aircall/connection'
      path: '/connection'
      fullPath: '/settings/aircall/connection'
      preLoaderRoute: typeof SettingsAircallConnectionRouteImport
      parentRoute: typeof SettingsAircallRoute
    }
    '/settings/ai/usage-log': {
      id: '/settings/ai/usage-log'
      path: '/usage-log'
      fullPath: '/settings/ai/usage-log'
      preLoaderRoute: typeof SettingsAiUsageLogRouteImport
      parentRoute: typeof SettingsAiRoute
    }
    '/settings/ai/tasks': {
      id: '/settings/ai/tasks'
      path: '/tasks'
      fullPath: '/settings/ai/tasks'
      preLoaderRoute: typeof SettingsAiTasksRouteImport
      parentRoute: typeof SettingsAiRoute
    }
    '/settings/ai/settings': {
      id: '/settings/ai/settings'
      path: '/settings'
      fullPath: '/settings/ai/settings'
      preLoaderRoute: typeof SettingsAiSettingsRouteImport
      parentRoute: typeof SettingsAiRoute
    }
    '/settings/ai/services': {
      id: '/settings/ai/services'
      path: '/services'
      fullPath: '/settings/ai/services'
      preLoaderRoute: typeof SettingsAiServicesRouteImport
      parentRoute: typeof SettingsAiRoute
    }
    '/settings/ai/prompts': {
      id: '/settings/ai/prompts'
      path: '/prompts'
      fullPath: '/settings/ai/prompts'
      preLoaderRoute: typeof SettingsAiPromptsRouteImport
      parentRoute: typeof SettingsAiRoute
    }
    '/settings/ai/health': {
      id: '/settings/ai/health'
      path: '/health'
      fullPath: '/settings/ai/health'
      preLoaderRoute: typeof SettingsAiHealthRouteImport
      parentRoute: typeof SettingsAiRoute
    }
    '/settings/ai/budget': {
      id: '/settings/ai/budget'
      path: '/budget'
      fullPath: '/settings/ai/budget'
      preLoaderRoute: typeof SettingsAiBudgetRouteImport
      parentRoute: typeof SettingsAiRoute
    }
  }
}

interface SettingsAiRouteChildren {
  SettingsAiBudgetRoute: typeof SettingsAiBudgetRoute
  SettingsAiHealthRoute: typeof SettingsAiHealthRoute
  SettingsAiPromptsRoute: typeof SettingsAiPromptsRoute
  SettingsAiServicesRoute: typeof SettingsAiServicesRoute
  SettingsAiSettingsRoute: typeof SettingsAiSettingsRoute
  SettingsAiTasksRoute: typeof SettingsAiTasksRoute
  SettingsAiUsageLogRoute: typeof SettingsAiUsageLogRoute
}

const SettingsAiRouteChildren: SettingsAiRouteChildren = {
  SettingsAiBudgetRoute: SettingsAiBudgetRoute,
  SettingsAiHealthRoute: SettingsAiHealthRoute,
  SettingsAiPromptsRoute: SettingsAiPromptsRoute,
  SettingsAiServicesRoute: SettingsAiServicesRoute,
  SettingsAiSettingsRoute: SettingsAiSettingsRoute,
  SettingsAiTasksRoute: SettingsAiTasksRoute,
  SettingsAiUsageLogRoute: SettingsAiUsageLogRoute,
}

const SettingsAiRouteWithChildren = SettingsAiRoute._addFileChildren(
  SettingsAiRouteChildren,
)

interface SettingsAircallRouteChildren {
  SettingsAircallConnectionRoute: typeof SettingsAircallConnectionRoute
  SettingsAircallNumbersRoute: typeof SettingsAircallNumbersRoute
  SettingsAircallSyncLogsRoute: typeof SettingsAircallSyncLogsRoute
  SettingsAircallUsersRoute: typeof SettingsAircallUsersRoute
  SettingsAircallWebhooksRoute: typeof SettingsAircallWebhooksRoute
}

const SettingsAircallRouteChildren: SettingsAircallRouteChildren = {
  SettingsAircallConnectionRoute: SettingsAircallConnectionRoute,
  SettingsAircallNumbersRoute: SettingsAircallNumbersRoute,
  SettingsAircallSyncLogsRoute: SettingsAircallSyncLogsRoute,
  SettingsAircallUsersRoute: SettingsAircallUsersRoute,
  SettingsAircallWebhooksRoute: SettingsAircallWebhooksRoute,
}

const SettingsAircallRouteWithChildren = SettingsAircallRoute._addFileChildren(
  SettingsAircallRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAiRoute: typeof SettingsAiRouteWithChildren
  SettingsAircallRoute: typeof SettingsAircallRouteWithChildren
  SettingsShopifyRoute: typeof SettingsShopifyRoute
  SettingsWorkspaceRoute: typeof SettingsWorkspaceRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAiRoute: SettingsAiRouteWithChildren,
  SettingsAircallRoute: SettingsAircallRouteWithChildren,
  SettingsShopifyRoute: SettingsShopifyRoute,
  SettingsWorkspaceRoute: SettingsWorkspaceRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SupportRouteChildren {
  SupportIndexRoute: typeof SupportIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportIndexRoute: SupportIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

interface TasksRouteChildren {
  TasksCalendarRoute: typeof TasksCalendarRoute
  TasksCustomerRoute: typeof TasksCustomerRoute
  TasksEmailRoute: typeof TasksEmailRoute
  TasksMessagesRoute: typeof TasksMessagesRoute
  TasksSalesRoute: typeof TasksSalesRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksCalendarRoute: TasksCalendarRoute,
  TasksCustomerRoute: TasksCustomerRoute,
  TasksEmailRoute: TasksEmailRoute,
  TasksMessagesRoute: TasksMessagesRoute,
  TasksSalesRoute: TasksSalesRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface TeamUsersRouteChildren {
  TeamUsersAddRoute: typeof TeamUsersAddRoute
  TeamUsersIndexRoute: typeof TeamUsersIndexRoute
}

const TeamUsersRouteChildren: TeamUsersRouteChildren = {
  TeamUsersAddRoute: TeamUsersAddRoute,
  TeamUsersIndexRoute: TeamUsersIndexRoute,
}

const TeamUsersRouteWithChildren = TeamUsersRoute._addFileChildren(
  TeamUsersRouteChildren,
)

interface TeamRouteChildren {
  TeamCommissionsRoute: typeof TeamCommissionsRoute
  TeamRolesRoute: typeof TeamRolesRoute
  TeamUsersRoute: typeof TeamUsersRouteWithChildren
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamCommissionsRoute: TeamCommissionsRoute,
  TeamRolesRoute: TeamRolesRoute,
  TeamUsersRoute: TeamUsersRouteWithChildren,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  B2bRequestsRoute: B2bRequestsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MailMarketingRoute: MailMarketingRoute,
  OrdersRoute: OrdersRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SupportRoute: SupportRouteWithChildren,
  SystemMailRoute: SystemMailRoute,
  TasksRoute: TasksRouteWithChildren,
  TeamRoute: TeamRouteWithChildren,
  SegmentsIndexRoute: SegmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
