/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestInvitationRouteImport } from './routes/request-invitation'
import { Route as ReorderRouteImport } from './routes/reorder'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PickupRouteImport } from './routes/pickup'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterTokenRouteImport } from './routes/register.$token'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestInvitationRoute = RequestInvitationRouteImport.update({
  id: '/request-invitation',
  path: '/request-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReorderRoute = ReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupRoute = PickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTokenRoute = RegisterTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => RegisterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/pickup': typeof PickupRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRouteWithChildren
  '/reorder': typeof ReorderRoute
  '/request-invitation': typeof RequestInvitationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/tracking': typeof TrackingRoute
  '/register/$token': typeof RegisterTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/pickup': typeof PickupRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRouteWithChildren
  '/reorder': typeof ReorderRoute
  '/request-invitation': typeof RequestInvitationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/tracking': typeof TrackingRoute
  '/register/$token': typeof RegisterTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/pickup': typeof PickupRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRouteWithChildren
  '/reorder': typeof ReorderRoute
  '/request-invitation': typeof RequestInvitationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/tracking': typeof TrackingRoute
  '/register/$token': typeof RegisterTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/cart'
    | '/documents'
    | '/forgot-password'
    | '/invoices'
    | '/login'
    | '/orders'
    | '/pickup'
    | '/products'
    | '/profile'
    | '/register'
    | '/reorder'
    | '/request-invitation'
    | '/reset-password'
    | '/support'
    | '/team'
    | '/tracking'
    | '/register/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/cart'
    | '/documents'
    | '/forgot-password'
    | '/invoices'
    | '/login'
    | '/orders'
    | '/pickup'
    | '/products'
    | '/profile'
    | '/register'
    | '/reorder'
    | '/request-invitation'
    | '/reset-password'
    | '/support'
    | '/team'
    | '/tracking'
    | '/register/$token'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/cart'
    | '/documents'
    | '/forgot-password'
    | '/invoices'
    | '/login'
    | '/orders'
    | '/pickup'
    | '/products'
    | '/profile'
    | '/register'
    | '/reorder'
    | '/request-invitation'
    | '/reset-password'
    | '/support'
    | '/team'
    | '/tracking'
    | '/register/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  CartRoute: typeof CartRoute
  DocumentsRoute: typeof DocumentsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PickupRoute: typeof PickupRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  ReorderRoute: typeof ReorderRoute
  RequestInvitationRoute: typeof RequestInvitationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  TrackingRoute: typeof TrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-invitation': {
      id: '/request-invitation'
      path: '/request-invitation'
      fullPath: '/request-invitation'
      preLoaderRoute: typeof RequestInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reorder': {
      id: '/reorder'
      path: '/reorder'
      fullPath: '/reorder'
      preLoaderRoute: typeof ReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup': {
      id: '/pickup'
      path: '/pickup'
      fullPath: '/pickup'
      preLoaderRoute: typeof PickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$token': {
      id: '/register/$token'
      path: '/$token'
      fullPath: '/register/$token'
      preLoaderRoute: typeof RegisterTokenRouteImport
      parentRoute: typeof RegisterRoute
    }
  }
}

interface RegisterRouteChildren {
  RegisterTokenRoute: typeof RegisterTokenRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterTokenRoute: RegisterTokenRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  CartRoute: CartRoute,
  DocumentsRoute: DocumentsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PickupRoute: PickupRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRouteWithChildren,
  ReorderRoute: ReorderRoute,
  RequestInvitationRoute: RequestInvitationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  TrackingRoute: TrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
