export const MEMBER_PERMISSIONS = {
  identityRead: 'identity.read',
  identityWrite: 'identity.write',
  membersRead: 'members.read',
  membersWrite: 'members.write',
  rolesRead: 'roles.read',
  rolesWrite: 'roles.write',
  customersRead: 'customers.read',
  customersWrite: 'customers.write',
  ordersRead: 'orders.read',
  ordersWrite: 'orders.write',
  pricingRead: 'pricing.read',
  pricingWrite: 'pricing.write',
  segmentsRead: 'segments.read',
  segmentsWrite: 'segments.write',
  supportRead: 'support.read',
  supportWrite: 'support.write',
  b2bAccessRead: 'b2b_access.read',
  b2bAccessWrite: 'b2b_access.write',
  settingsRead: 'settings.read',
  settingsWrite: 'settings.write',
  syncTrigger: 'sync.trigger',
  taskAssign: 'task.assign',
  aircallUsersRead: 'aircall.users.read',
  aircallUsersWrite: 'aircall.users.write',
  commissionSubmit: 'commission.submit',
} as const;

export const CUSTOMER_PERMISSIONS = {
  accountRead: 'account.read',
  accountWrite: 'account.write',
  subUsersRead: 'subusers.read',
  subUsersWrite: 'subusers.write',
  ordersRead: 'orders.read',
  ordersCreate: 'orders.create',
  spendingLimitsWrite: 'spending_limits.write',
} as const;

export type MemberPermission = (typeof MEMBER_PERMISSIONS)[keyof typeof MEMBER_PERMISSIONS];
export type CustomerPermission = (typeof CUSTOMER_PERMISSIONS)[keyof typeof CUSTOMER_PERMISSIONS];
export type Permission = MemberPermission | CustomerPermission;

export const DEFAULT_MEMBER_ROLES = [
  {
    slug: 'owner',
    name: 'Owner',
    description: 'Full workspace administration',
    permissions: Object.fromEntries(Object.values(MEMBER_PERMISSIONS).map((permission) => [permission, true])),
  },
  {
    slug: 'admin',
    name: 'Admin',
    description: 'Manage daily operations without tenant ownership controls',
    permissions: {
      [MEMBER_PERMISSIONS.identityRead]: true,
      [MEMBER_PERMISSIONS.membersRead]: true,
      [MEMBER_PERMISSIONS.membersWrite]: true,
      [MEMBER_PERMISSIONS.rolesRead]: true,
      [MEMBER_PERMISSIONS.customersRead]: true,
      [MEMBER_PERMISSIONS.customersWrite]: true,
      [MEMBER_PERMISSIONS.ordersRead]: true,
      [MEMBER_PERMISSIONS.ordersWrite]: true,
      [MEMBER_PERMISSIONS.pricingRead]: true,
      [MEMBER_PERMISSIONS.pricingWrite]: true,
      [MEMBER_PERMISSIONS.segmentsRead]: true,
      [MEMBER_PERMISSIONS.segmentsWrite]: true,
      [MEMBER_PERMISSIONS.supportRead]: true,
      [MEMBER_PERMISSIONS.supportWrite]: true,
      [MEMBER_PERMISSIONS.b2bAccessRead]: true,
      [MEMBER_PERMISSIONS.b2bAccessWrite]: true,
      [MEMBER_PERMISSIONS.settingsRead]: true,
      [MEMBER_PERMISSIONS.taskAssign]: true,
      [MEMBER_PERMISSIONS.aircallUsersRead]: true,
      [MEMBER_PERMISSIONS.aircallUsersWrite]: true,
    },
  },
  {
    slug: 'agent',
    name: 'Agent',
    description: 'Personnel workspace access',
    permissions: {
      [MEMBER_PERMISSIONS.identityRead]: true,
      [MEMBER_PERMISSIONS.customersRead]: true,
      [MEMBER_PERMISSIONS.ordersRead]: true,
      [MEMBER_PERMISSIONS.pricingRead]: true,
      [MEMBER_PERMISSIONS.segmentsRead]: true,
      [MEMBER_PERMISSIONS.supportRead]: true,
      [MEMBER_PERMISSIONS.supportWrite]: true,
      [MEMBER_PERMISSIONS.b2bAccessRead]: true,
      [MEMBER_PERMISSIONS.taskAssign]: true,
      [MEMBER_PERMISSIONS.aircallUsersRead]: true,
    },
  },
  {
    slug: 'customer_service',
    name: 'Customer Service',
    description: 'Inbound support and customer follow-up staff',
    permissions: {
      [MEMBER_PERMISSIONS.customersRead]: true,
      [MEMBER_PERMISSIONS.customersWrite]: true,
      [MEMBER_PERMISSIONS.supportRead]: true,
      [MEMBER_PERMISSIONS.supportWrite]: true,
      [MEMBER_PERMISSIONS.ordersRead]: true,
      [MEMBER_PERMISSIONS.segmentsRead]: true,
      [MEMBER_PERMISSIONS.taskAssign]: true,
      [MEMBER_PERMISSIONS.aircallUsersRead]: true,
    },
  },
  {
    slug: 'sales_personel',
    name: 'Sales Personel',
    description: 'Sales workspace staff with commission submission rights',
    permissions: {
      [MEMBER_PERMISSIONS.customersRead]: true,
      [MEMBER_PERMISSIONS.customersWrite]: true,
      [MEMBER_PERMISSIONS.ordersRead]: true,
      [MEMBER_PERMISSIONS.ordersWrite]: true,
      [MEMBER_PERMISSIONS.pricingRead]: true,
      [MEMBER_PERMISSIONS.pricingWrite]: true,
      [MEMBER_PERMISSIONS.segmentsRead]: true,
      [MEMBER_PERMISSIONS.taskAssign]: true,
      [MEMBER_PERMISSIONS.aircallUsersRead]: true,
      [MEMBER_PERMISSIONS.commissionSubmit]: true,
    },
  },
] as const;

export const DEFAULT_CUSTOMER_ROLES = [
  {
    slug: 'b2b_admin',
    name: 'B2B Admin',
    description: 'Manage company users and account settings',
    permissions: Object.fromEntries(Object.values(CUSTOMER_PERMISSIONS).map((permission) => [permission, true])),
  },
  {
    slug: 'b2b_user',
    name: 'B2B User',
    description: 'Place and review orders within assigned spending limits',
    permissions: {
      [CUSTOMER_PERMISSIONS.accountRead]: true,
      [CUSTOMER_PERMISSIONS.accountWrite]: true,
      [CUSTOMER_PERMISSIONS.ordersRead]: true,
      [CUSTOMER_PERMISSIONS.ordersCreate]: true,
    },
  },
] as const;
