export const MEMBER_PERMISSIONS = {
  identityRead: 'identity.read',
  identityWrite: 'identity.write',
  membersRead: 'members.read',
  membersWrite: 'members.write',
  rolesRead: 'roles.read',
  rolesWrite: 'roles.write',
  customersRead: 'customers.read',
  customersWrite: 'customers.write',
  ordersRead: 'orders.read',
  ordersWrite: 'orders.write',
  pricingRead: 'pricing.read',
  pricingWrite: 'pricing.write',
  segmentsRead: 'segments.read',
  segmentsWrite: 'segments.write',
  supportRead: 'support.read',
  supportWrite: 'support.write',
  messagingRead: 'messaging.read',
  messagingWrite: 'messaging.write',
  b2bAccessRead: 'b2b_access.read',
  b2bAccessWrite: 'b2b_access.write',
  settingsRead: 'settings.read',
  settingsWrite: 'settings.write',
  mailTemplateRead: 'mail.template.read',
  mailTemplateWrite: 'mail.template.write',
  mailTemplateApprove: 'mail.template.approve',
  mailTemplatePublish: 'mail.template.publish',
  mailDeliveryRead: 'mail.delivery.read',
  mailDeliveryRetry: 'mail.delivery.retry',
  mailSuppressionRead: 'mail.suppression.read',
  mailSuppressionWrite: 'mail.suppression.write',
  mailSettingsRead: 'mail.settings.read',
  mailSettingsWrite: 'mail.settings.write',
  mailMarketingContactRead: 'mail.marketing.contact.read',
  mailMarketingContactWrite: 'mail.marketing.contact.write',
  mailMarketingAudienceRead: 'mail.marketing.audience.read',
  mailMarketingAudienceWrite: 'mail.marketing.audience.write',
  mailMarketingCampaignRead: 'mail.marketing.campaign.read',
  mailMarketingCampaignWrite: 'mail.marketing.campaign.write',
  mailMarketingCampaignApprove: 'mail.marketing.campaign.approve',
  mailMarketingCampaignPublish: 'mail.marketing.campaign.publish',
  mailMarketingFlowRead: 'mail.marketing.flow.read',
  mailMarketingFlowWrite: 'mail.marketing.flow.write',
  mailMarketingFlowPublish: 'mail.marketing.flow.publish',
  syncTrigger: 'sync.trigger',
  taskAssign: 'task.assign',
  aircallUsersRead: 'aircall.users.read',
  aircallUsersWrite: 'aircall.users.write',
  commissionSubmit: 'commission.submit',
} as const;

export const CUSTOMER_PERMISSIONS = {
  accountRead: 'account.read',
  accountWrite: 'account.write',
  subUsersRead: 'subusers.read',
  subUsersWrite: 'subusers.write',
  ordersRead: 'accounts.order.read_own',
  ordersCreate: 'accounts.order.create_own',
  ordersReorder: 'accounts.order.reorder_own',
  invoicesRead: 'accounts.invoice.read_own',
  cartWrite: 'accounts.cart.write_own',
  spendingLimitsWrite: 'spending_limits.write',
} as const;

export type MemberPermission = (typeof MEMBER_PERMISSIONS)[keyof typeof MEMBER_PERMISSIONS];
export type CustomerPermission = (typeof CUSTOMER_PERMISSIONS)[keyof typeof CUSTOMER_PERMISSIONS];
export type Permission = MemberPermission | CustomerPermission;
export type MemberSurface = 'admin' | 'person';

const ADMIN_SURFACE_PERMISSIONS = [
  MEMBER_PERMISSIONS.settingsRead,
  MEMBER_PERMISSIONS.settingsWrite,
  MEMBER_PERMISSIONS.membersRead,
  MEMBER_PERMISSIONS.membersWrite,
  MEMBER_PERMISSIONS.rolesRead,
  MEMBER_PERMISSIONS.rolesWrite,
  MEMBER_PERMISSIONS.mailTemplateRead,
  MEMBER_PERMISSIONS.mailDeliveryRead,
  MEMBER_PERMISSIONS.mailMarketingContactRead,
] as const;

export function memberSurfaceFromPermissions(permissions: readonly string[] = []): MemberSurface {
  return ADMIN_SURFACE_PERMISSIONS.some((permission) => permissions.includes(permission)) ? 'admin' : 'person';
}

export function isAdminSurfacePermissions(permissions: readonly string[] = []) {
  return memberSurfaceFromPermissions(permissions) === 'admin';
}

export function isPersonSurfacePermissions(permissions: readonly string[] = []) {
  return memberSurfaceFromPermissions(permissions) === 'person';
}

export const DEFAULT_MEMBER_ROLES = [
  {
    slug: 'owner',
    name: 'Owner',
    description: 'Full workspace administration',
    permissions: Object.fromEntries(Object.values(MEMBER_PERMISSIONS).map((permission) => [permission, true])),
  },
  {
    slug: 'admin',
    name: 'Admin',
    description: 'Manage daily operations without tenant ownership controls',
    permissions: {
      [MEMBER_PERMISSIONS.identityRead]: true,
      [MEMBER_PERMISSIONS.membersRead]: true,
      [MEMBER_PERMISSIONS.membersWrite]: true,
      [MEMBER_PERMISSIONS.rolesRead]: true,
      [MEMBER_PERMISSIONS.customersRead]: true,
      [MEMBER_PERMISSIONS.customersWrite]: true,
      [MEMBER_PERMISSIONS.ordersRead]: true,
      [MEMBER_PERMISSIONS.ordersWrite]: true,
      [MEMBER_PERMISSIONS.pricingRead]: true,
      [MEMBER_PERMISSIONS.pricingWrite]: true,
      [MEMBER_PERMISSIONS.segmentsRead]: true,
      [MEMBER_PERMISSIONS.segmentsWrite]: true,
      [MEMBER_PERMISSIONS.supportRead]: true,
      [MEMBER_PERMISSIONS.supportWrite]: true,
      [MEMBER_PERMISSIONS.messagingRead]: true,
      [MEMBER_PERMISSIONS.messagingWrite]: true,
      [MEMBER_PERMISSIONS.b2bAccessRead]: true,
      [MEMBER_PERMISSIONS.b2bAccessWrite]: true,
      [MEMBER_PERMISSIONS.settingsRead]: true,
      [MEMBER_PERMISSIONS.mailTemplateRead]: true,
      [MEMBER_PERMISSIONS.mailTemplateWrite]: true,
      [MEMBER_PERMISSIONS.mailTemplateApprove]: true,
      [MEMBER_PERMISSIONS.mailTemplatePublish]: true,
      [MEMBER_PERMISSIONS.mailDeliveryRead]: true,
      [MEMBER_PERMISSIONS.mailDeliveryRetry]: true,
      [MEMBER_PERMISSIONS.mailSuppressionRead]: true,
      [MEMBER_PERMISSIONS.mailSuppressionWrite]: true,
      [MEMBER_PERMISSIONS.mailSettingsRead]: true,
      [MEMBER_PERMISSIONS.mailSettingsWrite]: true,
      [MEMBER_PERMISSIONS.mailMarketingContactRead]: true,
      [MEMBER_PERMISSIONS.mailMarketingContactWrite]: true,
      [MEMBER_PERMISSIONS.mailMarketingAudienceRead]: true,
      [MEMBER_PERMISSIONS.mailMarketingAudienceWrite]: true,
      [MEMBER_PERMISSIONS.mailMarketingCampaignRead]: true,
      [MEMBER_PERMISSIONS.mailMarketingCampaignWrite]: true,
      [MEMBER_PERMISSIONS.mailMarketingCampaignApprove]: true,
      [MEMBER_PERMISSIONS.mailMarketingCampaignPublish]: true,
      [MEMBER_PERMISSIONS.mailMarketingFlowRead]: true,
      [MEMBER_PERMISSIONS.mailMarketingFlowWrite]: true,
      [MEMBER_PERMISSIONS.mailMarketingFlowPublish]: true,
      [MEMBER_PERMISSIONS.taskAssign]: true,
      [MEMBER_PERMISSIONS.aircallUsersRead]: true,
      [MEMBER_PERMISSIONS.aircallUsersWrite]: true,
    },
  },
  {
    slug: 'agent',
    name: 'Agent',
    description: 'Personnel workspace access',
    permissions: {
      [MEMBER_PERMISSIONS.identityRead]: true,
      [MEMBER_PERMISSIONS.customersRead]: true,
      [MEMBER_PERMISSIONS.ordersRead]: true,
      [MEMBER_PERMISSIONS.pricingRead]: true,
      [MEMBER_PERMISSIONS.segmentsRead]: true,
      [MEMBER_PERMISSIONS.supportRead]: true,
      [MEMBER_PERMISSIONS.supportWrite]: true,
      [MEMBER_PERMISSIONS.messagingRead]: true,
      [MEMBER_PERMISSIONS.messagingWrite]: true,
      [MEMBER_PERMISSIONS.b2bAccessRead]: true,
      [MEMBER_PERMISSIONS.taskAssign]: true,
      [MEMBER_PERMISSIONS.aircallUsersRead]: true,
    },
  },
  {
    slug: 'customer_service',
    name: 'Customer Service',
    description: 'Inbound support and customer follow-up staff',
    permissions: {
      [MEMBER_PERMISSIONS.customersRead]: true,
      [MEMBER_PERMISSIONS.customersWrite]: true,
      [MEMBER_PERMISSIONS.supportRead]: true,
      [MEMBER_PERMISSIONS.supportWrite]: true,
      [MEMBER_PERMISSIONS.messagingRead]: true,
      [MEMBER_PERMISSIONS.messagingWrite]: true,
      [MEMBER_PERMISSIONS.ordersRead]: true,
      [MEMBER_PERMISSIONS.segmentsRead]: true,
      [MEMBER_PERMISSIONS.taskAssign]: true,
      [MEMBER_PERMISSIONS.aircallUsersRead]: true,
    },
  },
  {
    slug: 'sales_personel',
    name: 'Sales Personel',
    description: 'Sales workspace staff with commission submission rights',
    permissions: {
      [MEMBER_PERMISSIONS.customersRead]: true,
      [MEMBER_PERMISSIONS.customersWrite]: true,
      [MEMBER_PERMISSIONS.ordersRead]: true,
      [MEMBER_PERMISSIONS.ordersWrite]: true,
      [MEMBER_PERMISSIONS.pricingRead]: true,
      [MEMBER_PERMISSIONS.pricingWrite]: true,
      [MEMBER_PERMISSIONS.segmentsRead]: true,
      [MEMBER_PERMISSIONS.supportRead]: true,
      [MEMBER_PERMISSIONS.supportWrite]: true,
      [MEMBER_PERMISSIONS.messagingRead]: true,
      [MEMBER_PERMISSIONS.messagingWrite]: true,
      [MEMBER_PERMISSIONS.taskAssign]: true,
      [MEMBER_PERMISSIONS.aircallUsersRead]: true,
      [MEMBER_PERMISSIONS.commissionSubmit]: true,
    },
  },
] as const;

export const DEFAULT_CUSTOMER_ROLES = [
  {
    slug: 'b2b_admin',
    name: 'B2B Admin',
    description: 'Manage company users and account settings',
    permissions: Object.fromEntries(Object.values(CUSTOMER_PERMISSIONS).map((permission) => [permission, true])),
  },
  {
    slug: 'b2b_user',
    name: 'B2B User',
    description: 'Place and review orders within assigned spending limits',
    permissions: {
      [CUSTOMER_PERMISSIONS.accountRead]: true,
      [CUSTOMER_PERMISSIONS.accountWrite]: true,
      [CUSTOMER_PERMISSIONS.ordersRead]: true,
      [CUSTOMER_PERMISSIONS.ordersCreate]: true,
      [CUSTOMER_PERMISSIONS.ordersReorder]: true,
      [CUSTOMER_PERMISSIONS.invoicesRead]: true,
      [CUSTOMER_PERMISSIONS.cartWrite]: true,
    },
  },
] as const;
